sudo: required
language: php
services:
  - mysql
matrix:
  fast_finish: true
  include:
  - php: 7.2
  - php: 7.1
    env: SKIP_STYLE_CHECK=1
  - php: 7.0
    env: SKIP_STYLE_CHECK=1
  - php: 5.6
    env: SKIP_STYLE_CHECK=1 EXECUTE_BUILD_DOCS=true
#  - php: hhvm
#    env: SKIP_STYLE_CHECK=1

  allow_failures:
  - php: hhvm

cache:
  directories:
    - vendor
    - $HOME/.cache/pip
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y snmp fping
  - mysql -e 'CREATE DATABASE librenms_phpunit_78hunjuybybh;'

install:
  - composer install --prefer-dist --no-interaction
  - pip install --user snmpsim pylint mysql-python

after_failure:
  - tail /tmp/snmpsimd.log

script:
  - php scripts/pre-commit.php -l
  - php scripts/pre-commit.php -s
  - php scripts/pre-commit.php -u --db --snmpsim --fail-fast
  - bash -n daily.sh
  - pylint -E poller-wrapper.py discovery-wrapper.py

before_deploy:
  - cd ..
  - tar -zcf ${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-alldeps.tar.gz librenms

deploy:
  provider: releases
  api_key:
    secure: "ONxjg1LoARVxMcx13zz8xFMhKDHahbFtHABXa4Nl0R+dXN7CykTnS7M3+EfPXEPDUA8C62AUSJJPM5f+mH4NdUVE7pW0vWy6BPWNArMriVwpAT3Q37TOpGmg4N4IxoV/9TH2nA+wG6I9N1aEbYyu6mTIRM65dMa7blzz5QVvaV1oMEbOIvZfl5J9ZA6HXAm/KOGsP+x9oDJntLJQfNzhFz4lrppKkCYq19kdEOQVYgrj1cHeardfGXTe4aZwkMuL7mHsGj7QfZoUlT8V9IdO/EkocxrFhkQNxSzuci9qTpcOhrzCa6oeSYt7bOa/h1XKHgOZVLRQ5tYLJooLxBkAhrx+AWul1gPl0RmMMugniWxGtxEBT83jPWQvS6qkPJSOv8eliLCNQVVgAO6IjCKv8TPdrdV/JO548wXwzEc8qqa4w4qJxluZbcivjlJ6rw0Uannb7YL+z0rLi3V7otwu94CSL2TbiNj9foaeHYxcEyJJ6J7IhVMyAvNMSivXlmZDzODKVMjbHrEA62HaY8qZ7+acUmkNwnII+6z/0LiciWRP6351vHM3PInQ5+ZyoL23M+hKfFDtyIkAOrGRGhQr17JARMNaGrXIgu5/Rpp/Qg96OsxMnj7ulTyEc1fUY9WS4fOwEiLP0PpbZfOmUSxv8NIJwMIoe++mQwvK0rEbMt0="
  file: ${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-alldeps.tar.gz
  skip_cleanup: true
  on:
    tags: true
